#
# Makefile
#
usage:
	@echo "usage: make [edit|build|run|open]"

edit e:
	vi src/main.rs

edit-toml et:
	vi Cargo.toml

build b:
	cargo build

run r:
	cargo run

open o:
	open https://crates.io/crates/gstreamer


git-update gu:
	cd ..; make gu

