#
# Makefile for gstreamer app in rust
#
usage:
	@echo "usage: make [edit|build|run|open]"

edit e:
	vi src/main.rs

edit-toml et:
	vi Cargo.toml

build b:
	cargo build
build-release br:
	cargo build --release

run r:
	cargo run
run-release rr:
	cargo run --release

open o:
	open https://crates.io/crates/gstreamer


git-update gu:
	cd ..; make gu

